#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
    ctags --tag-relative -L - -f"$dir/$$.tags" --fields=+l
mv "$dir/$$.tags" "$dir/tags"

trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git
mv .git/tags.$$ .git/tags
